import { describe, expect, it } from 'vitest'
import type { CapmResponse } from '../api/client'
import {
  DEFAULT_CAPM_SETTINGS, applyGlobalBounds, buildCapmRequest, capmRows, capmSummary,
  allViewsZero, calChartData, capmApplyLines, capmApplyPlan, capmCsv, capmCsvFilename, capmTradeRows, capmWeightSource, defaultHoldingInputs, defaultTargetValue, formatBeta, formatReturn, formatView, parseTargetValue, rfLabel, sameCapmRun, statItems, varItems, viewEffect,
} from './capm'
import type { CapmRun } from './capm'
import type { Portfolio } from './portfolio'
import type { TradeBasis } from './optimize'

const RESPONSE: CapmResponse = {
  tickers: ['A', 'B', 'Y'],
  holdings: [
    { ticker: 'A', current_weight: 0.4, target_weight: 0.6, beta: 1.5, capm_return: 0.115, view: 0.2, expected_return: 0.125, vol: 0.286243, frozen: false, pinned: false, first_bar: '2021-01-04' },
    { ticker: 'B', current_weight: 0.4, target_weight: 0.2, beta: 0.5, capm_return: 0.065, view: 0, expected_return: 0.065, vol: 0.177594, frozen: true, pinned: false, first_bar: '2021-01-04' },
    { ticker: 'Y', current_weight: 0.2, target_weight: 0.2, beta: 0.793333, capm_return: 0.0796667, view: -0.1, expected_return: 0.0746667, vol: 0.169006, frozen: false, pinned: true, first_bar: '2024-06-03' },
  ], current_weights: { A: 0.4, B: 0.4, Y: 0.2 }, target_weights: { A: 0.6, B: 0.2, Y: 0.2 },
  metrics: { expected_return: 0.0979333, expected_vol: 0.219962, expected_sharpe: 0.263379, portfolio_beta: 1.158667 },
  current_metrics: { expected_return: 0.0901, expected_vol: 0.2, expected_sharpe: 0.2412, portfolio_beta: 0.9587 },
  var_95: { daily: -0.0224, weekly: -0.0483, monthly: -0.0963, quarterly: -0.1564, annual: -0.2639 },
  rf: 0.0427, rf_source: 'live', mrp: 0.05, market_ticker: 'SPY', lookback_days: 1825, fit_start: '2021-09-27', fit_end: '2026-09-25', score_start: '2024-06-04', warnings: [],
}
const PORTFOLIO: Portfolio = { id: 'p1', name: 'Test', cashWeight: 10, positions: [{ ticker: 'A', weight: 50 }, { ticker: 'B', weight: 40 }], updatedAt: '2026-09-26T00:00:00.000Z' }
const WEIGHTS_BASIS: TradeBasis = { kind: 'weights', reason: 'no-shares' }
const DOLLAR_BASIS: TradeBasis = { kind: 'dollar', investedValue: 900, prices: { A: 100, B: 50 }, shares: { A: 5, B: 8 } }
const DOLLAR3: Extract<TradeBasis, { kind: 'dollar' }> = { kind: 'dollar', investedValue: 1000, prices: { A: 100, B: 50, Y: 20 }, shares: { A: 4, B: 8, Y: 10 } }
const PORTFOLIO3: Portfolio = { id: 'p3', name: 'Test', cashWeight: 10, positions: [{ ticker: 'A', weight: 36, shares: 4 }, { ticker: 'B', weight: 36, shares: 8 }, { ticker: 'Y', weight: 18, shares: 10 }], updatedAt: '2026-09-26T00:00:00.000Z' }
const CLOSES3 = new Map<string, number | null>([['A', 100], ['B', 50], ['Y', 20]])

describe('capm helpers', () => {
  it('creates default holding inputs in position order', () => { const inputs = defaultHoldingInputs(PORTFOLIO); expect(inputs).toEqual({ A: { freeze: false, viewPct: 0, minPct: '0', maxPct: '100' }, B: { freeze: false, viewPct: 0, minPct: '0', maxPct: '100' } }); expect(Object.keys(inputs)).toEqual(['A', 'B']) })
  it('applies global bounds without changing frozen or source values', () => { const inputs = defaultHoldingInputs(PORTFOLIO); inputs.B = { ...inputs.B, freeze: true }; const next = applyGlobalBounds(inputs, '5', '50'); expect(next.A).toEqual({ freeze: false, viewPct: 0, minPct: '5', maxPct: '50' }); expect(next.B).toEqual(inputs.B); expect(inputs.A.minPct).toBe('0') })
  it('builds a weights-basis request', () => { const inputs = defaultHoldingInputs(PORTFOLIO); inputs.A = { freeze: false, viewPct: -20, minPct: '10', maxPct: '60' }; expect(buildCapmRequest(PORTFOLIO, DEFAULT_CAPM_SETTINGS, inputs, WEIGHTS_BASIS)).toEqual({ ok: true, request: { tickers: ['A', 'B'], weights: [50, 40], lookback_days: 1825, rf: null, mrp: 0.05, market_ticker: 'SPY', configs: { A: { freeze: false, view: -0.2, min_weight: 0.1, max_weight: 0.6 }, B: { freeze: false, view: 0, min_weight: 0, max_weight: 1 } } } }) })
  it('builds dollar-basis weights', () => { const result = buildCapmRequest(PORTFOLIO, DEFAULT_CAPM_SETTINGS, defaultHoldingInputs(PORTFOLIO), DOLLAR_BASIS); expect(result.ok && result.request.weights).toEqual([500, 400]) })
  it('keeps explicit risk-free zero manual', () => { const manual = buildCapmRequest(PORTFOLIO, { ...DEFAULT_CAPM_SETTINGS, rfPct: '4.5' }, defaultHoldingInputs(PORTFOLIO), WEIGHTS_BASIS); expect(manual.ok && manual.request.rf).toBeCloseTo(.045, 12); const zero = buildCapmRequest(PORTFOLIO, { ...DEFAULT_CAPM_SETTINGS, rfPct: '0' }, defaultHoldingInputs(PORTFOLIO), WEIGHTS_BASIS); expect(zero.ok && zero.request.rf).toBe(0) })
  it.each([
    [{ marketTicker: '  ' }, 'Choose a market ticker.'], [{ rfPct: '20' }, 'Risk-free rate must be at least 0% and below 20%, or blank for the live 3-month T-bill rate.'], [{ rfPct: '-0.5' }, 'Risk-free rate must be at least 0% and below 20%, or blank for the live 3-month T-bill rate.'], [{ rfPct: 'abc' }, 'Risk-free rate must be at least 0% and below 20%, or blank for the live 3-month T-bill rate.'], [{ mrpPct: '0' }, 'Market risk premium must be above 0% and at most 20%.'], [{ mrpPct: '' }, 'Market risk premium must be above 0% and at most 20%.'], [{ mrpPct: '25' }, 'Market risk premium must be above 0% and at most 20%.'], [{ input: ['A', 'minPct', ''] }, 'A: min and max weight must be numbers.'], [{ input: ['B', 'maxPct', 'x'] }, 'B: min and max weight must be numbers.'],
  ] as Array<[{ marketTicker?: string; rfPct?: string; mrpPct?: string; input?: [string, 'minPct' | 'maxPct', string] }, string]>)('validates %o', (change, message) => { const settings = { ...DEFAULT_CAPM_SETTINGS, ...change }; const inputs = defaultHoldingInputs(PORTFOLIO); if (change.input) inputs[change.input[0]] = { ...inputs[change.input[0]], [change.input[1]]: change.input[2] }; expect(buildCapmRequest(PORTFOLIO, settings, inputs, WEIGHTS_BASIS)).toEqual({ ok: false, message }) })
  it('compares recorded runs', () => { const run: CapmRun = { settings: DEFAULT_CAPM_SETTINGS, inputs: defaultHoldingInputs(PORTFOLIO) }; expect(sameCapmRun(run, structuredClone(run))).toBe(true); expect(sameCapmRun(run, { ...run, inputs: { ...run.inputs, A: { ...run.inputs.A, viewPct: 5 } } })).toBe(false); expect(sameCapmRun(run, { ...run, settings: { ...run.settings, mrpPct: '4' } })).toBe(false); expect(sameCapmRun(run, { ...run, inputs: { ...run.inputs, Z: run.inputs.A } })).toBe(false) })
  it('maps result rows', () => { const rows = capmRows(RESPONSE); expect(rows.map((row) => row.ticker)).toEqual(['A', 'B', 'Y']); expect(rows[0].change).toBeCloseTo(.2, 12); expect(rows[1].change).toBeCloseTo(-.2, 12); expect(rows[2].change).toBe(0); expect(rows[1].frozen).toBe(true); expect(rows[2].pinned).toBe(true); expect(rows[0]).toMatchObject({ beta: 1.5, expectedReturn: .125 }) })
  it('formats each view effect at the current market risk premium', () => { expect(viewEffect(20, '5')).toBe('+1.00%/yr'); expect(viewEffect(-50, '5')).toBe('-2.50%/yr'); expect(viewEffect(100, '8')).toBe('+8.00%/yr'); expect(viewEffect(15, '5')).toBe('+0.75%/yr'); expect(viewEffect(0, '5')).toBeNull(); expect(viewEffect(20, '')).toBeNull(); expect(viewEffect(20, 'abc')).toBeNull(); expect(viewEffect(20, '0')).toBeNull(); expect(viewEffect(20, '25')).toBeNull() })
  it('formats values', () => { expect([formatReturn(.115), formatReturn(.0746667), formatReturn(-.0224), formatReturn(-.00001)]).toEqual(['11.50%', '7.47%', '-2.24%', '0.00%']); expect([formatView(.2), formatView(0), formatView(-.1), formatView(-.05)]).toEqual(['+20%', '0%', '-10%', '-5%']); expect([formatBeta(.793333), formatBeta(1.5)]).toEqual(['0.79', '1.50']) })
  it('labels risk-free sources', () => { expect(rfLabel(.0427, 'live')).toBe('4.27% (3-month T-bill)'); expect(rfLabel(.0427, 'fallback')).toBe('4.27% (fallback, live rate unavailable)'); expect(rfLabel(.0427, 'manual')).toBe('4.27% (entered)') })
  it('summarises the run', () => expect(capmSummary(RESPONSE)).toBe('5Y lookback · market SPY · risk-free 4.27% (3-month T-bill) · MRP 5.00% · fitted 2021-09-27 → 2026-09-25'))
  it('labels custom lookbacks in the summary', () => expect(capmSummary({ ...RESPONSE, lookback_days: 183 })).toContain('183-day lookback'))
  it('builds statistic tiles', () => { expect(statItems(RESPONSE).map(({ label, value }) => [label, value])).toEqual([['Expected return', '9.79%'], ['Expected volatility', '22.00%'], ['Expected Sharpe', '0.26'], ['Beta vs SPY', '1.16']]); expect(statItems({ ...RESPONSE, metrics: { ...RESPONSE.metrics, expected_sharpe: null } })[2].value).toBe('—'); expect(statItems(RESPONSE)[2].tooltip).toContain('4.27% (3-month T-bill)') })
  it('builds value-at-risk tiles', () => expect(varItems(RESPONSE).map(({ label, value }) => [label, value])).toEqual([['Daily', '-2.24%'], ['Weekly', '-4.83%'], ['Monthly', '-9.63%'], ['Quarterly', '-15.64%'], ['Annual', '-26.39%']]))
  it('parses target values', () => { expect(parseTargetValue('')).toEqual({ ok: true, value: null }); expect(parseTargetValue('  ')).toEqual({ ok: true, value: null }); expect(parseTargetValue('1,500')).toEqual({ ok: true, value: 1500 }); expect(parseTargetValue('$1,500.50')).toEqual({ ok: true, value: 1500.5 }); expect(parseTargetValue(' 900 ')).toEqual({ ok: true, value: 900 }); for (const text of ['0', '-5', 'abc', 'Infinity']) expect(parseTargetValue(text)).toEqual({ ok: false, message: 'Target value must be a dollar amount above $0, or blank.' }) })
  it('defaults target value', () => { expect(defaultTargetValue(DOLLAR3)).toBe('1000.00'); expect(defaultTargetValue({ ...DOLLAR3, investedValue: 123456.789 })).toBe('123456.79'); expect(defaultTargetValue(WEIGHTS_BASIS)).toBe('') })
  it('maps CAPM weights into shared trade source', () => { const source = capmWeightSource(RESPONSE); expect(source.implied_trades.A).toBeCloseTo(.2); expect(source.implied_trades.B).toBeCloseTo(-.2); expect(source.implied_trades.Y).toBe(0); expect(source.pinned).toEqual([{ ticker: 'Y' }]) })
  it('sizes CAPM trades to target value', () => { for (const [value, expected] of [[1000, [[400, 6, 600, 2, 200, false], [400, 4, 200, -4, -200, true], [200, 10, 200, 0, 0, false]]], [1500, [[400, 9, 900, 5, 500, false], [400, 6, 300, -2, -100, true], [200, 15, 300, 5, 100, false]]]] as const) { expect(capmTradeRows(RESPONSE, DOLLAR3, value).map((row) => [row.currentValue, row.targetShares, row.targetValue, row.tradeShares, row.tradeValue, row.frozen])).toEqual(expected) } })
  it('adds dollar detail to VaR', () => { expect(varItems(RESPONSE, 1000).map((item) => item.detail)).toEqual(['-$22.40', '-$48.30', '-$96.30', '-$156.40', '-$263.90']); expect('detail' in varItems(RESPONSE)[0]).toBe(false) })
  it('builds current statistic tiles', () => { expect(statItems(RESPONSE, 'current').map(({ label, value }) => [label, value])).toEqual([['Expected return', '9.01%'], ['Expected volatility', '20.00%'], ['Expected Sharpe', '0.24'], ['Beta vs SPY', '0.96']]); expect(statItems(RESPONSE, 'current')[1].tooltip).toContain('Current weights') })
  it('recognizes all-zero views', () => { expect(allViewsZero(RESPONSE)).toBe(false); expect(allViewsZero({ ...RESPONSE, holdings: RESPONSE.holdings.map((holding) => ({ ...holding, view: 0 })) })).toBe(true) })
  it('exports CAPM CSV', () => { const weights = 'ticker,beta,capm_return_pct,view_pct,expected_return_pct,vol_pct,current_pct,target_pct,change_pp,frozen,pinned\nA,1.5,11.5,20,12.5,28.62,40,60,20,false,false\nB,0.5,6.5,0,6.5,17.76,40,20,-20,true,false\nY,0.7933,7.97,-10,7.47,16.9,20,20,0,false,true\n'; expect(capmCsv(RESPONSE, WEIGHTS_BASIS, 1000)).toBe(weights); expect(capmCsv(RESPONSE, DOLLAR3, null)).toBe(weights); expect(capmCsv(RESPONSE, DOLLAR3, 1500)).toBe('ticker,beta,capm_return_pct,view_pct,expected_return_pct,vol_pct,current_pct,target_pct,change_pp,frozen,pinned,price,current_shares,current_value,target_shares,target_value,trade_shares,trade_value\nA,1.5,11.5,20,12.5,28.62,40,60,20,false,false,100,4,400,9,900,5,500\nB,0.5,6.5,0,6.5,17.76,40,20,-20,true,false,50,8,400,6,300,-2,-100\nY,0.7933,7.97,-10,7.47,16.9,20,20,0,false,true,20,10,200,15,300,5,100\n') })
  it('names CAPM CSV files', () => expect(capmCsvFilename('My: Fund', new Date(2026, 8, 26))).toBe('My Fund-capm-2026-09-26.csv'))
  it('builds CAPM apply plans and lines', () => { const plan = capmApplyPlan(PORTFOLIO3, RESPONSE, CLOSES3); expect(plan).toMatchObject({ ok: true, sharesMode: 'recomputed', removed: [] }); if (plan.ok) { expect(plan.portfolio.positions).toMatchObject([{ ticker: 'A', weight: 54, shares: 6 }, { ticker: 'B', weight: 18, shares: 4 }, { ticker: 'Y', weight: 18, shares: 10 }]); expect(capmApplyLines(plan, DOLLAR3, 1000)).toEqual(['Holdings weights will be replaced by the Target column. Cash stays at 10.0%.', "Share counts will be recalculated from each holding's last stored close, as fractional shares.", 'There is no undo.']); expect(capmApplyLines(plan, DOLLAR3, 1500)[2]).toBe('Share counts are sized to the current invested value ($1,000.00), not the $1,500.00 Target value.') } })
  it('creates CAL chart data', () => { const data = calChartData(RESPONSE); expect(data.rf.vol).toBe(0); expect(data.rf.ret).toBeCloseTo(4.27); expect(data.target.vol).toBeCloseTo(21.9962, 4); expect(data.target.ret).toBeCloseTo(9.79333, 4); expect(data.current).toEqual({ vol: 20, ret: 9.01 }); expect(data.assets.map((asset) => asset.ticker)).toEqual(['A', 'B', 'Y']); expect(data.assets[0]).toMatchObject({ vol: 28.6243, ret: 12.5 }); expect(data.line[1].vol).toBeCloseTo(31.48673, 4); expect(data.line[1].ret).toBeCloseTo(12.17644, 4); expect(calChartData({ ...RESPONSE, metrics: { ...RESPONSE.metrics, expected_vol: 0 } }).line).toEqual([]) })
})
